version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/index.js
    - package.json
  discard-paths: yes

cache:
  paths:
    - node_modules

eb_codebuild_settings:
  CodeBuildServiceRole: CodeBuildServiceRoleForElasticBeanstalk
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
  Timeout: 5
